---
features:
  - |
    Add a new configuration option called "ovn_emit_need_to_frag" to
    the "ovn" section of etc/neutron/plugins/ml2_conf.ini. This new
    option tells ovn whether it should emit "need to frag" packets
    in case of MTU mismatch. Before enabling this configuration make
    sure that its supported by the host kernel (version >= 5.2) or
    by checking the output of the following command: ovs-appctl -t
    ovs-vswitchd dpif/show-dp-features br-int | grep "Check pkt length
    action". Defaults to False.
