- project:
    templates:
      - puppet-openstack-check-jobs
      - puppet-openstack-module-unit-jobs
      - puppet-openstack-integration-jobs-all
      - puppet-openstack-beaker-jobs
      - release-notes-jobs-python3
    check:
      jobs:
        - puppet-neutron-tripleo-standalone
    gate:
      jobs:
        - puppet-neutron-tripleo-standalone

- job:
    name: puppet-neutron-tripleo-standalone
    parent: tripleo-puppet-ci-centos-7-standalone
    description: |
      TripleO standalone Job running Neutron specific Tempest tests.
    vars:
      build_container_images: true
      featureset_override:
        run_tempest: false
        tempest_test_whitelist:
          - 'tempest.api.network'
          - 'tempest.scenario.test_network_basic_ops'
          - 'neutron_tempest_plugin.api'
        use_os_tempest: true
